name: Require Checklist

on:
  workflow_run:
    workflows: ["Dynamic PR Checklist"]
    types:  [completed]
  issue_comment:
    types: [edited] 

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/require-checklist-action@v2
        with:
          requireChecklist: false # If this is true and there are no checklists detected, the action will fail
          issueNumber: ${{ github.event.workflow_run.pull_requests[0].number }}
